## Basic Configuration
baseurl = "https://ihazcloudthings.xyz"
languageCode = "en"
title = "ihaz cloud things"
theme = "mainroad"
summarylength = 30
paginate = 10

disqusShortname = "ihazcloudthings"
# googleAnalytics = "your-google-analytics-id"
enableRobotsTXT = true

[Author] # Used in authorbox
  name = "Dustin Scott"
  bio = "Dustin is a Senior Cloud Native Field Engineer currently working for VMware"
  avatar = "img/dscott.jpg"

## Site Settings
[Params]
  subtitle = "tech blog"
  descriptions = "yet another tech blog"
  dateformat = "Jan 2, 2006"
  twitter_cards = true
  opengraph = true
  readmore = true
  authorbox = true
  toc = true
  post_navigation = true
  post_meta = ["date", "categories", "translations"]
  mainSections = ["posts", "about", "blog", "news"]
  mathjax = true
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js"
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML"
  highlightColor = "#e22d30"
  customCSS = ["/css/custom.css"]
#  customJS = ["/js/custom.js"]

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = false  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  #widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  widgets = ["recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 10
  tags_counter = true

## Social Accounts
[Params.widgets.social]
  github = "scottd018"
  linkedin = "dustin-scott-36a95190"
  twitter = "ihazcloud"
  # facebook = "username"
  # instagram = "username"
  # telegram = "username"
  # gitlab = "username"
  # bitbucket = "username"
  # email = "example@example.com"

# Custom social links
#[[Params.widgets.social.custom]]
#  title = "Youtube"
#  url = "https://youtube.com/user/username"
#  icon = "youtube.svg" # Optional. Path relative to "layouts/partials"

#[[Params.widgets.social.custom]]
#  title = "My Home Page"
#  url = "http://example.com"

## Top Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = -1000
  [[menu.main]]
    identifier = "about"
    name = "about me"
    url = "/about/"
    weight = 0
  [[menu.main]]
    name = "posts"
    url = "/posts/"
    weight = 100
